version: "3"
services:
  web:
  # fuel_web:
    # container_name: fuel_web
    image: nginx:latest
    ports:
      - '${APP_LISTEN_PORT:-15432}:{APP_FORWARD_PORT:-5432}'
    volumes:
      - ./docker/php/html:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php
      # - fuel_php

  php:
  # fuel_php:
    # container_name: fuel_php
    build: ./docker/php
    depends_on:
      - db
      # - fuel_db

  db:
  # fuel_db:
    # container_name: fuel_db
    image: postgres:14.1
    build: ./docker/postgres
    ports: 
      - '${DB_LISTEN_PORT:-15432}:{DB_FORWARD_PORT:-5432}'
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USER:-app_dev}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
      PGPASSWORD: '${PGPASSWORD:-password}'
      TZ: ${TZ:-Asia/Tokyo}
    # restart: always

  pgadmin4:
  # fuel_pgadmin4:
    # container_name: fuel_pgadmin4
    image: dpage/pgadmin4
    ports:
        - '${PGADMIN_FORWARD_PORT:-8081}:${PGADMIN_LISTEN_PORT:-81}'
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL:-pgadmn4@example.com}'
        PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-password}'
        PGADMIN_LISTEN_PORT: '${PGADMIN_LISTEN_PORT:-81}'
    hostname: pgadmin4
    depends_on: 
      - db
      # - fuel_db
    restart: always

volumes:
  postgres:
  pgadmin:
