version: "3"
services:
  fuel_web:
    container_name: fuel_web
    image: nginx:latest
    ports: ["8080:80"]
    volumes:
      - ./docker/php/html:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - fuel_php

  fuel_php:
    container_name: fuel_php
    build: ./docker/php
    depends_on:
      - fuel_db

  fuel_db:
    container_name: fuel_db
    image: postgres:14.1
    build: ./docker/postgres
    ports: [15432:5432]
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: app_dev
      POSTGRES_PASSWORD: pass
      PGPASSWORD: pswd
      TZ: Asia/Tokyo
    restart: always

  fuel_pgadmin4:
    image: dpage/pgadmin4
    container_name: fuel_pgadmin4
    ports:
        - 8081:81
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: root@example.com
        PGADMIN_DEFAULT_PASSWORD: pass
        PGADMIN_LISTEN_PORT: 81
    hostname: pgadmin4
    depends_on: 
      - fuel_db
    restart: always

volumes:
  postgres:
  pgadmin:
